name: rsue_schedule
description: Приложение для получения расписания для групп РГЭУ (РИНХ) в режиме реального времени
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_localization: ^0.1.10
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.0
  schedule_api:
    path: packages/schedule_api
  shared_preferences: ^2.0.18
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
