name: schedule_api
description: API для получения расписания с сервера.
version: 1.0.0

environment:
  sdk: '>=2.18.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  dio: ^4.0.6
  sqflite: ^2.2.5
  intl: ^0.18.0

